title: Mi página | Programador web 
author: GitHub User
email: joelmp3@live.com
description: > # this means to ignore newlines until "baseurl:"
  Soy un ingeniero en mecatrónica que se dedica a la programación web. Me gusta trabajar con php y estoy aprendiendo a usar otras tecnologias (como React.js)
  I'm a mechatronic engineeer who works in web programming. I like to work with php and i'm learning to use some other technologies (like React.js)
  
theme: minima

# social links
twitter_username: # DO NOT include the @ character, or else the build will fail!
github_username:  Davel99 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
